### ISSUE TITLE
Updater fails on OVH shared hosting

### ISSUE THREAD

**Issue by Swiiney** [nextcloud/updater#137]
(Issues moved from server issues : [Updater fails on OVH shared hosting #5878](https://github.com/nextcloud/updater/issues/137))

**Steps to reproduce**
1. Buy an OVH "Perso" hosting plan
2. Install Nextcloud 11.0.0 (stable) using the PHP online installer file
3. Try to run the updater

**Actual behaviour**
Be greeted by the following

> To login you need to provide the unhashed value of "updater.secret" in your config file.
> If you don't know that value, you can access this updater directly via the Nextcloud admin screen or generate your own secret:
> ```
> php -r '$password = trim(shell_exec("openssl rand -base64 48"));if(strlen($password) === 64) {$hash = password_hash($password, PASSWORD_DEFAULT) . "\n"; echo "Insert as \"updater.secret\": ".$hash; echo "The plaintext value is: ".$password."\n";}else{echo "Could not execute OpenSSL.\n";};'
> ```
Don't know any secret.
Impossible to run the command on mutualized hosting

**Expected behaviour**
Updater should run

**Server configuration**
[http://pro.ovh.net/infos/](https://github.com/nextcloud/updater/issues/137)
Operating system: Debian GNU/Linux 8.8 (jessie)
Web server: Apache/2.2.22
Database: MySQL 5.6.34-log
PHP version: 7.1.3
Nextcloud version: 11.0.0 (stable)

**Comments**
Where did you install Nextcloud from: PHP online installer file of ftp transfer of full scripts
If you upload the full new version, upgrade is done correctly.

**Comment by MorrisJobke** [comment]
There is a button in the admin settings to open the updater called "Open updater" when there is an update available. This  does then those steps for you. (see https://docs.nextcloud.com/server/12/admin_manual/maintenance/update.html#using-the-web-based-updater)

Beside that you can also run this php command locally and not on your server, because it only calculates an hash, that then needs to be written to the config.php itself.

Please ask for in the forums for help if something is unclear: https://help.nextcloud.com

**Comment by Swiiney** [comment]
Tried to execute the command locally. Unfortunatly when you enter the Hash in the config file it is not maintained after running the updater again.
Update is not passible.

**Comment by mrjive** [comment]
Same here, update is not possible.
