### ISSUE TITLE
Update 12.0.0 --->> 12.0.3 - fails on local DEBIAN 9 System

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/updater#144]
Hi, 

If I press update button I only receive the message:

Aktualisierungsfunktion konnte nicht gestartet werden, bitte versuche ein mauelles Update

And I have to manually update the server!

Why do i have to do it all over again each time I would like to update the server ???

Each update - minor or major - is ALWAYS a MAJOR headache!

My advice: NEVER UPDATE A running NC server! It only gives you a big headache !

Regards, Hitam4450

**Comment by LukasReschke** [comment]
My advice: ALWAYS post bug reports with more information such as which PHP version, what web server as well as the exact error message. (I don't find the string "bitte versuche ein mauelles Update" in the translation sources)

Regards, LukasReschke

**Comment by hitam4450** [comment]
Well thanks for your feedback! 
The message shows up in the middle at the top of the screen including the typing error in german language!

PHP Version 7.0.19-1, Lighttpd 1.4.35, DEBIAN 9.1

**Comment by MorrisJobke** [comment]
This is in the updatenotfication app even before the updater is started: https://github.com/nextcloud/server/blob/93994b1320960eac4d24999310d8ff0a2063975c/apps/updatenotification/js/admin.js#L47

This has very few to do with the actual updater because it already fails to load it. Could you please report this in the server repo and then also check the network console when clicking the button.

Thanks

@nickvergessen should know more here.
