### ISSUE TITLE
NC 13 Beta Updater stuck

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/updater#149]
Hi,

I installed a test instance on my server with the latest beta some days ago. After one successful update (I am on the **daily** channel running Nextcloud 13.0.0 Beta 1 Build:2017-11-16T22:01:20+00:00 ba150e5721cfa40a1e980003d92afde6f5068f29) the updater is kind of stuck. In settings -> basic settings I can see a new update being available but the update does not work.

I click on "open updater"...

<img width="713" alt="bildschirmfoto 2017-11-19 um 11 40 05" src="https://user-images.githubusercontent.com/8535968/32989849-9c899452-cd1e-11e7-9fed-f1eb72832620.png">

and on the next page, the individual tasks are already marked as done ... When I click "continue update" ...

<img width="633" alt="bildschirmfoto 2017-11-19 um 11 40 14" src="https://user-images.githubusercontent.com/8535968/32989850-9fa627f4-cd1e-11e7-9aba-e6781899ce28.png">

... nothing happens.

<img width="629" alt="bildschirmfoto 2017-11-19 um 11 40 24" src="https://user-images.githubusercontent.com/8535968/32989852-a32872e2-cd1e-11e7-97c5-0d2eae271fa9.png">

I also tried running `php occ upgrade` but this told me `Nextcloud is already latest version`.

**Comment by MorrisJobke** [comment]
That looks like the updater step is not properly reset (done in a repair step after the update)

Could you delete the file updater-INSTANCEID/.step from the data folder and try again?

occ upgrade will not download new version but only run the migration steps (see the update section in the docs)

**Comment by ho1ger** [comment]
Great. Thanks. I found and deleted the file. Afterwards the update worked as expected. 

However, after the update I found a new version of that file including the same issue as I have described earlier.

**Comment by MorrisJobke** [comment]
> However, after the update I found a new version of that file including the same issue as I have described earlier.

Yes - it is created on every run of the updater. Usually this is removed during the migration steps. See https://github.com/nextcloud/server/blob/master/lib/private/Repair/MoveUpdaterStepFile.php

However this is only called if there is actually a upgrade. So if you use the daily channel it could be that this is not properly triggered. But on the other side we usually cleanup in the last step of the updater: https://github.com/nextcloud/updater/blob/3b002cf6e03cdd95b6e06789d92176c64f63d723/index.php#L1038

Could you send over the updater.log from the nextcloud data dir and append it to ticket #85 because that is the thing you experienced.

Thanks
