### ISSUE TITLE
updater.phar always disables all apps in non-interactive mode

### ISSUE THREAD

**Issue by smueller18** [nextcloud/updater#174]
Using the updater.phar from the command line with the option `--non-interaction` always disables all apps. In the updater.phar, the upgrade command is set to `./occ upgrade` https://github.com/nextcloud/updater/blob/bf17b097677499e22716f107009566bc83dbf6c0/lib/UpdateCommand.php#L295
In the [docker-entrypoint.sh](https://github.com/nextcloud/docker/blob/5ea9f6b612dc3ec4e5aac7cde9f4fcb767730be7/docker-entrypoint.sh#L53) of the docker image the command is called with `--no-app-disable`.
Is there any reason why this option is not integrated in the updater.phar? If there is no reason against I could create a pull request. I think adding an additional command line parameter to the updater.phar is the best choice.

**Comment by MorrisJobke** [comment]
Which PHP Version do you use? Because this is only the case for PHP 5.6. we recommend to upgrade to PHP 7+ anyways. Also it would cause more harm if we forcefully keep all apps enabled. There was a reason why they get disabled: it could be that they crash the server hard and the instance needs to be fixed on the command line otherways.

Thus I will close this here. And if this is still a problem report it in the server repo, because the updater.phar just replaces the code and then calls server code to do the migration.

**Comment by smueller18** [comment]
My php version on the CLI is 7.0.27. I don't understand why the `--no-app-disable` then is set in the docker entrypoint. Is there no possibility for a system crash?

Nevertheless, I do get your point. But for my use case (without docker using the updater.phar), it would make sense either to give the possibility not to run the occ upgrade command in non-interactive mode, or introduce an optional parameter to call the occ upgrade from within the updater.phar with the `--no-app-disable` option. Both options are currently not supported.

Here is the log of my recent update:
```
bash-4.3$ /usr/local/php70/bin/php --version
PHP 7.0.27 (cli) (built: Jan  5 2018 11:39:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

bash-4.3$ /usr/local/php70/bin/php ./updater/updater.phar --no-interaction
Nextcloud Updater - version: v13.0.0beta1

Current version is 13.0.2.

Update to Nextcloud 13.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-13.0.4.zip

Updater run in non-interactive mode.

Start update

Info: Gracefully stopping the updater via Ctrl-C is not possible - PCNTL extension is not loaded.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.
Updater run in non-interactive mode - will start "occ upgrade" now.

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled 3rd-party app: apporder
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: end_to_end_encryption
Disabled 3rd-party app: files_downloadactivity
Disabled 3rd-party app: groupfolders
Disabled 3rd-party app: metadata
Disabled 3rd-party app: passman
Disabled 3rd-party app: polls
Disabled 3rd-party app: registration
Disabled 3rd-party app: tasks
Disabled 3rd-party app: twofactor_totp
Updating <oauth2> ...
Updated <oauth2> to 1.1.1
Updating <dav> ...
Fix broken values of calendar objects

 Starting ...
    0/0 [>---------------------------]   0%
Updated <dav> to 1.4.7
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_external in appstore
Checked for update of app "files_external" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore 
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level

Updater run in non-interactive mode - will disable maintenance mode now.

Maintenance mode is disabled

```

**Comment by MorrisJobke** [comment]
Regarding the docker I have no feedback and this should be discussed in that repo. But it could be that this is a known env and then seen as valid approach (only valid if no apps from the AppStore can be installed – otherwise this can lead to a broken instance)

On which Nextcloud version are you? Because the disabling should not happen and it would be good to know why it happen.

**Comment by smueller18** [comment]
As you can see in the logs above, I was on 13.0.2 and updated to 13.0.4 this morning:

```
Nextcloud Updater - version: v13.0.0beta1

Current version is 13.0.2.

Update to Nextcloud 13.0.4 available. (channel: "stable")
```

If you have a look at the logs above, you see the section where it disables all 3rd party apps.

**Comment by MorrisJobke** [comment]
Could you open a ticket in the server repo as this is not related to the updater

**Comment by MorrisJobke** [comment]
> So if I get you right, if I run just ./occ upgrade, no 3rd party apps should be disabled? But then I don't understand why there is an --no-app-disable option for the occ upgrade command.

This was added to enforce it also on PHP5.6 for people that are 100% sure, that they will continue to work.

Background of this: In PHP 7+ it is possible to detect even syntax issues and properly catch problems on this side. Thus we can gracefully catch problems and disable the responsible app. In PHP before 7.0 this was not possible and just immediately stopped the PHP runtime and thus the server needs to be restored by going on the CLI and remove the app from a given table in the database to restore the server to work again. So we went for the "better save than sorry" approach and disabled all 3rdparty apps (as in "not shipped by default"), because there we don't know if they will work under all supported PHP versions.

With PHP 7.0+ we went for the new approach and usually don't disable it again. Let me check the code again to be sure that this is still all the case.

**Comment by MorrisJobke** [comment]
We even removed it in Nextcloud 14 (because it is PHP 7.0+ only):

It is present in stable13: https://github.com/nextcloud/server/blob/stable13/core/Command/Upgrade.php#L80-L85

But not anymore in current master:

https://github.com/nextcloud/server/blob/0ad1f19a74a52e270b488dc04ffbbfd692cd68ce/core/Command/Upgrade.php#L77-L79

And here is the code that removes the "disable 3rdparty apps" code: https://github.com/nextcloud/server/pull/7955

So this should not happen at all with the next version of the server (planned for August) because there the code that disables 3rdparty apps is not present at all ;)

**Comment by smueller18** [comment]
Thanks, that information was helpful. So I am looking forward for the next release ;-)
