### ISSUE TITLE
Can't activate some apps after upgrading to NC14.0.3

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/updater#190]
Screenshot after upgrading with the web updater:
![update-nc-13-14-disabled-apps](https://user-images.githubusercontent.com/24833757/47309559-0c228600-d635-11e8-8b00-64f320899ad6.png)

In the new version of Nextcloud i could update those apps but i am unable to activate them.

Screenshot of deactivated apps _after_ upgrading them:

![nc14-deactivated-apps](https://user-images.githubusercontent.com/24833757/47309695-67547880-d635-11e8-860c-f248fcf5a99e.png)

How to activate them again?

**Comment by MorrisJobke** [comment]
This is completely handled in the server: https://github.com/nextcloud/server

But for those apps simply the update to Nextcloud 14 is missing. Even if I thin that for most of them an update should be available via the App Store. Looking at the time window: this could be right about the time when GitHub (for the archives) and our app store (for the metadata) had issues. Could you retry now and check if those apps provide an update for you? Otherwise open an issue in the server repo.

**Comment by Sanookmakmak** [comment]
Now i could update all of them except the Ebook reader. This one ist still unavailable for NC14 unfortunately.

**Comment by MorrisJobke** [comment]
> Now i could update all of them except the Ebook reader. This one ist still unavailable for NC14 unfortunately.

Try to reach out to the maintainer of this app. This is unfortunately out of our hands.
