### ISSUE TITLE
NC13.0.6 does not update to 13.07

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/updater#191]
Screenshot of Settings Page:

![nc1307-available](https://user-images.githubusercontent.com/24833757/47310320-0168f080-d637-11e8-96d4-f64238862b61.png)

Screenshot of web updater. Does not update to 13.0.7!
![nc1306-not-updating-to-1307](https://user-images.githubusercontent.com/24833757/47310330-06c63b00-d637-11e8-9256-959d7e930a3a.png)

**Comment by MorrisJobke** [comment]
Currently we don't have a way to lockdown the version. The web UI sends some more information and thus can get a different version. The updater itself will always get the latest version on the channel. It's a bit tricky and something like nextcloud/updater#189 would help to avoid this issue in the future. Nevertheless this only happens when we do staged rollouts, because then the web UI in the settings will maybe get into a different pool than the updater.

And yes the change to production works, because there we don't yet ship 14, but will soon do so AFAIK.


See also https://github.com/nextcloud/server/issues/11818#issuecomment-430517581

As of now it works as it should and we plan to improve (see linked ticket)

Thanks for the feedback anyway.
