### ISSUE TITLE
Auto updater doesn't work

### ISSUE THREAD

**Issue by 0xNeffarion** [nextcloud/updater#200]
I'm using Nextcloud 15 RC1. I have gotten a notification to update to 15 RC3. However the auto updater doesn't work at all.

Updater page:

![Updater](https://i.imgur.com/CIoVCCM.png)

Once I click the start update button, nothing happens. I checked the JS console and got the following:

![console](https://i.imgur.com/oAyNywq.jpg)

I'm using Firefox by the way

**Comment by MorrisJobke** [comment]
This was a bug in the RC 1. It is fixed in 15.0.0 RC 2, but only after it is installed. As of now you can only use the `updater.phar` in the `updater/` directory that needs to be called from the CLI.

See https://github.com/nextcloud/server/pull/12713 for details about the fix.

Sorry for the inconvenience.
