### ISSUE TITLE
Ignore asset folder

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/updater#23]

**Comment by MorrisJobke** [comment]
When?

**Comment by LukasReschke** [comment]
When doing the check for extra folders. Doesn't hurt to backup the folder though.

See also https://help.nextcloud.com/t/test-our-new-work-in-progress-upgrader-script/1214/59?u=lukasreschke

**Comment by ricardo777** [comment]
I have the same issue, with the folders

.well-known
stats

First is for letsencrypt en second for awstats generated by the control panel.

**Comment by LukasReschke** [comment]
> The update cannot fo further now, maybe a ignore or skip button or config would be handy.

That's the expected behaviour. We won't support situations were people have placed custom folders in their Nextcloud folder.

**Comment by rigrig** [comment]
Looks like this is not necessary anymore, now that the asset pipeline is removed? (https://github.com/nextcloud/server/commit/72464f1ce49b16049e0c82aedf2f740b50ec1991)
(I think people deleting the folder is preferable to the updater ignoring it, because we don't want unused folders hanging around)

Somewhere[1] it should probably be mentioned to the user that
* the ```assets``` folder was for the asset pipeline
* the pipeline is removed in newer versions, so the folder can(and should) be safely deleted
* older NC versions might still have the pipeline option, but it's probably a good idea to disable it (see #https://github.com/nextcloud/server/issues/215 and https://help.nextcloud.com/t/asset-pipeline-enabled-leads-to-a-blank-calendar-with-error/1122/5)
* even with the pipeline enabled it can be safely deleted before upgrading (I think. It would be regenerated after the update, right?)

[1] Not sure where, it could be put as special case into the updater, or simply told to users when they come ask about it on the forum, or added to the update documentation.

**Comment by tx7** [comment]
Hi,

I understand that you guys don't want users to place any custom folder in there for security purpose, but this is for Let's Encrypt encryption, not just any folder.
Not everybody can afford to buy a official certificate for his/her domain.
That's why Let's Encrypt exist for users like me to use.
Please re-consider this.

Thanks.

**Comment by LukasReschke** [comment]
> I understand that you guys don't want users to place any custom folder in there for security purpose, but the .well-known folder is for Let's Encrypt's encryption, not just any folder.

We also use LetsEncrypt for our infrastructure but configure LetsEncrypt in a way that the configuration happens in the VirtualHost.

**Comment by tx7** [comment]
That's for Apache.
Nginx is a different though.

**Comment by LukasReschke** [comment]
https://community.letsencrypt.org/t/how-to-nginx-configuration-to-enable-acme-challenge-support-on-all-http-virtual-hosts/5622 should help there.

**Comment by tx7** [comment]
I see.
From what I'm reading, I input the codes in Nginx for NextCloud, and create an alias that link to the actual .well-known folder?

`location ^~ /.well-known/acme-challenge/ {
  alias /var/www/acme-challenge/;
}`

**Comment by MorrisJobke** [comment]
> From what I'm reading, I input the codes in Nginx for NextCloud, and create an alias that link to the actual .well-known folder?

Yes. That's correct. Please post questions about setup in our forums: https://help.nextcloud.com/
 (this is the bug tracker ;))

**Comment by Ralf99** [comment]
> We won't support situations were people have placed custom folders in their Nextcloud folder.

@LukasReschke 
I understood your intention and it´s honorable of you but for people like me (with a shared Webspace) the updater won´t work in future. Because my Provider (all-inkl.com) put
/cgi-bin
/logs
/usage
Folders in every root domain with no posibility to delete.
How can I solve this?

**Comment by ThomasCr** [comment]
how about a feature, that owncloud/nextcloud give there customers a way, to generate a file which is signed by owncloud/nextcloud, which they can put in there installation directory. this file has the additionals files/folders which are allowed in the root folder. This file should be signen only to specific domain, to prevent attacks. User has to response with a mail to the domain owner (postmaster or hostmaster) to check that he is the owner of the domain...

**Comment by grzchr15** [comment]
To your on risk:
Not a full blown solution but a workaround that works
Open file https://yourserver/yournextcloudir/updater/index.php
search for getExpectedElementsList()
Update list that it fits to your needs ( add logs and usage as permitted directory )
Save it
Update Nextcloud with automatic updater
done

your change to this files gets reverted during update to the release version, 
but updater worked to new release

**Comment by Ralf99** [comment]
@grzchr15 
Thanks for this hint!
When I add my three folders to this list, I get a "OK" for the first check but unfortunately I stop at the next step "Check for write permissions" :(
The new STOP-Message is this:

> Check for write permissions
> The following places can not be written to:
> /www/htdocs/xxx/updater/../cgi-bin/cgi-fpm/.htaccess
> /www/htdocs/xxx/updater/../cgi-bin/cgi-fpm/.
> /www/htdocs/xxx/updater/../logs/access_log_2017-05-15

Do you have further ideas??

**Comment by MorrisJobke** [comment]
Asset folder is not available anymore. For all the other folders: they should not be in the Nextcloud folder and indicate a possible problem.

**Comment by retide** [comment]
I have to delete my asset folder each time I do a new update, but it keeps reappearing (e.g. update 11.0.1 to 11.0.2, now 11.0.2 to 11.0.3). Its not a big deal, but a tiny bit annoying. Does anyone know why the folder reappears and how to get rid of it once and for all?

**Comment by rigrig** [comment]
@retide I think setting `'asset-pipeline.enabled' => false,` in your config.php should prevent the asset folder from being re-generated.
(Assuming you have good reasons to not simply upgrade to the latest Nextcloud version, where the whole asset pipeline has been removed)

**Comment by retide** [comment]
@rigrig Thanks for your response. I made a mistake above: all 11 should be 12, i.e. I am on the latest version, but the folder still keeps reappearing. Sorry about the confusion.

**Comment by rigrig** [comment]
Well, in that case this should definitely not happen, as the assets pipeline has been removed.

It's probably best if you open a new issue about the asset folder being created.
If it only happens during updates then https://github.com/nextcloud/updater/issues/new would be the place to report it, but if it also reappears during normal operation you should probably report it at https://github.com/nextcloud/server/issues/new instead.

**Comment by iromeister** [comment]
Just to get this right: So Nextcloud is not supposed to be installed at the root of a domain or subdomain at all?
