### ISSUE TITLE
Verify integrity failed - No signature specified for defined update

### ISSUE THREAD

**Issue by apiening** [nextcloud/updater#247]
I'm trying to upgrade a OwnCloud 8.2.9 instance to NextCloud.
I've downloaded the updater.phar (v16.0.3-3-ga0c2b25 dirty from stable17) in the updater/ - folder and started it via `sudo -u www-data php updater.phar`.
The version of my install is detected correctly and after the checks and backup steps the nextcloud archive is downloaded from https://download.nextcloud.com/server/releases/nextcloud-9.0.58.zip
After this, I get the error:
```
[✘] Verify integrity failed
No signature specified for defined update

Update failed. To resume or retry just execute the updater again.
```
Any suggestion on how to solve this is highly appreciated.

**Comment by joshtrichards** [comment]
Hi @apiening Thanks for your report! 

The place to look for details of problems when running updater is the `updater.log` file. Since this was so long ago I imagine you've long since moved passed beyond this issue (I hope!). 

In the future, please post over at the [Nextcloud Help Forum](https://help.nextcloud.com/) for general assistance inquiries regarding installation/configuration matters. GitHub is mostly used for reporting bugs and prioritizing enhancement ideas. All Issues are read to prioritize development resources, but may not receive an individual response.

**Comment by joshtrichards** [comment]
I was re-reading your old issue in order to close it out and I realized you mentioned ownCloud:

> I'm trying to upgrade a OwnCloud 8.2.9 instance to NextCloud.
I've downloaded the updater.phar (v16.0.3-3-ga0c2b25 dirty from stable17) in the updater/ - folder and started it via `sudo -u www-data php updater.phar`

The recommended approach was (and is) to use the *Manual* upgrade approach. The Updater can't be used until you've already completed the *Manual* upgrade.

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/migrating_owncloud.html
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html
