### ISSUE TITLE
NC 17 update is not shown in the updater

### ISSUE THREAD

**Issue by HLFH** [nextcloud/updater#250]
Hi,

I quote `cmcloughlin`:

> I waited a month for 17 to show and then followed the advice to switch to beta. Now with 16.0.6 RC1 installed it’s saying I’m up to date.
I have tried using
sudo -u www-data php /usr/share/nginx/nextcloud/updater/updater.phar
and get the message
“Current version is 16.0.6 RC1
No update available”
I also tried
sudo …/updater/occ upgrade
and get
“Nextcloud is already the latest version”

How can we upgrade to Nextcloud 17 from 16.0.6 RC1 with the Nextcloud updater?

**Comment by toxpal** [comment]
The same issue with all NC installations for me as well - https://help.nextcloud.com/t/update-to-nextcloud-17-not-available/61204/15?u=toxpal

**Comment by HLFH** [comment]
In the meantime, the [manual update to NC17](https://docs.nextcloud.com/server/17/admin_manual/maintenance/manual_upgrade.html) works. 
For step 12, with the new Nextcloud and the old config.php, I am able to use the web-based updated instead of the command line. I have not had to install any 3rd-party apps, it seems Nextcloud was taking care of them. 

I wanted to upgrade to NC 17 because of the last updates of Nextcloud Mail that require you to use NC 17.

**Comment by toxpal** [comment]
A quick update...

2 days ago I updated all installations of NC from 16.0.5 to 17 **manually**. CLI updater didn't work because of famous **must be of the type string, null given** error, but I was able to finish update using web interface. 

Today, I logged in to one of upgraded installations and got a notification - _upgrade to 17.0.1 available_. Great, updates work again! Not really... When I open Settings -> Overview, it displays - **17.0.0. - Your version is up to date**.

Tried to cleanup cache, force reload, etc - notification popup about 17.0.1 is always displayed, but NC says that I'm running the latest version (17.0.0). So it looks separate NC modules conflict between themselves.

But wait, there's more. I opened another NC installation (which also had problems with upgrade, so I had to upgrade it manually) and no matter what I do, I couldn't get notification popup about v17.0.1 to get displayed. But when I opened Settings -> Overview, it instantly offered to upgrade to 17.0.1, and automatic update worked perfectly.

Both installations are located on the **same server** and have very similar setup (except some apps), so I believe there's something really wrong about NC updater...

**Comment by stefan123t** [comment]
Same here I just finished upgrade from 16.0.3 -> 16.0.7 on 23/12/2019 but there is no option to upgrade to 17.0.1 now that I am on the latest 16.0.x version.

Any pointers on why that is or what I need to check ?

I have seen #258 is asking also what to check for the Update Availabilty Check, IMHO it would be good to know what goes wrong in this case.

**Comment by toxpal** [comment]
I solved this issue with all installations by performing manual upgrade (as per NC documentation). After that, all installations started working just fine again - automatic updates can be downloaded and applied as soon as they are available.

**Comment by PVince81** [comment]
likely outdated, in some cases the updates were not pushed yet to the update server and only appear a bit later

if the problem persists, feel free to reopen
