### ISSUE TITLE
Step 5 is currently in process.

### ISSUE THREAD

**Issue by dacoex** [nextcloud/updater#272]
My instance is running on 17.0.3

The admin web site shows that version 17.0.4 is available to upgrade.

After hitting upgrade, it fails.
`Step 5 is currently in process. Please reload this page later.`

Using the command line via ssh shows that system runs already on latest version:
```
/usr/bin/php71 ./occ upgrade
Cannot load Zend OPcache - it was already loaded
Nextcloud is already latest version
```

After running 
/usr/bin/php71 ./occ maintenance:repair

And then trying to upgrade in the web-interface, the error says:

> Check for expected files
> Parsing response failed.
> 

```

**Comment by nazar-pc** [comment]
Exact same issue here when attempting an upgrade from 19.0.6.2 to 20.0.4.0.

Also fails with web-interface with:
```
Verifying integrity
Parsing response failed.
Show detailed response
```

CLI says "Nextcloud is already latest version" and refreshing updater page results in "Step 5 is currently in process. Please reload this page later."

**Comment by klimentyev** [comment]
@nazar-pc I've the same problem too.

**Comment by klimentyev** [comment]
I updated from command line: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#using-the-command-line-based-updater
Before I deleted .step file: https://github.com/nextcloud/nextcloudpi/issues/411#issuecomment-409393252

**Comment by nazar-pc** [comment]
Interesting. `php occ upgrade` didn't want to upgrade, but with `php updater/updater.phar` turned out updater wanted to consume more memory than PHP was allowed to use. Now it makes sense, though web updater didn't handle it gracefully and I'm wondering why a lot of memory is needed to verify integrity.

With `php -d memory_limit=1024M updater/updater.phar` everything worked fine, thanks for the hint!

**Comment by klimentyev** [comment]
I was able to update my small server with `memory_limit=512M` in PHP config.

**Comment by uwemock** [comment]
Is there a way to get around this limitation?

I have no way to raise my the memory limit on my installation.

**Comment by stephang** [comment]
If the upgrade process failed earlier, your updated is stuck with this message.

> Step 5 is currently in process. Please reload this page later.

"Step 5" is validating the download, so no production files should have been touched yet. In that case you can try to completely cancel the upgrade process.

- go to your data dir (example: `/var/www/nextcloud/data`)
- here, you should have a directory with all the update files (`updater-[INSTANCE_ID]`)
- remove / rename the file `.step`
- re-open the updater

**Comment by marcelklehr** [comment]
There should really be some kind of --reset or --force param :/

**Comment by tomtom** [comment]
In a shared web-hosting environment, step 5 seems to fail due to memory restrictions. The updater stops with an error. It seems to me, we can skip step 5 by editing the `.step` file and by replacing "start" with "end". Could somebody with intimate knowledge of NC please verify that this is a sensible thing to do?

**Comment by tomtom** [comment]
Maybe the updater could work with a zip file that was downloaded & verified & put in a specific folder by the user beforehand?

**Comment by tijmcraft** [comment]
https://alaskalinuxuser3.ddns.net/2021/07/29/nextcloud-step-5-is-currently-in-process/

**Comment by tomtom** [comment]
> https://alaskalinuxuser3.ddns.net/2021/07/29/nextcloud-step-5-is-currently-in-process/ <https://alaskalinuxuser3.ddns.net/2021/07/29/nextcloud-step-5-is-currently-in-process/>

This assumes you can change the memory limit, which you sometimes can't.

**Comment by joshtrichards** [comment]
> Now it makes sense, though web updater didn't handle it gracefully and I'm wondering why a lot of memory is needed to verify integrity.

The Updater requires memory at least equal to size of the current Archive file: See #505 for some analysis.

At present, Archive sizes are about ~220MB so assume you need at least 256MB for the `verifyIntegrity()` step (5). Unsurprisingly this has increased over the years. With Server v18 it was ~100MB.

> Is there a way to get around this limitation? I have no way to raise my the memory limit on my installation.

Yes, do a manual update which will always work in environments where the Updater can't be used: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html

> There should really be some kind of --reset or --force param :/

`occ maintenance:repair` automatically clears out a `.step` file if one does not wish to do it manually.

> In a shared web-hosting environment, step 5 fails (most likely) due to memory restrictions. The updater stops with an error. All other recommendations for dealing with this situation don't really work in such an environment.

A manual update will always work if the Updater won't work in your environment:  https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html

**Comment by tomtom** [comment]
Thank you very much for looking into this.

In an environment where you cannot set the php memory limit, you most
likely also don't have shell access to do a manual update.

As written earlier, it would be nice if the updater provided an option to
skip a step or to use a custom archive that was validated beforehand.
Another option could be to split the archive into smaller parts, validate
the parts, and then combine them again. Originally, I was hoping there is a
streaming alternative to the checksum function so that there is no need to
load the whole file into memory.
