### ISSUE TITLE
Updater is not offering 17.0.5 to a server with 17.0.4 currently installed

### ISSUE THREAD

**Issue by Lozrus** [nextcloud/updater#278]
I have a server with NC17.0.4 currently installed, on an Ubuntu 18.04 x64 dedicated server, hosted with Apache 2.4.29, PHP 7.2.24 and MariaDB 15.1. It is on the "Stable" update channel.
The updater is currently offering 18.0.3 as an update, not  the recent 17.0.5 security update.

I understand that Nextcloud would probably like people to switch to NC18, but I am not quite ready yet due to certain plugins. It's not entirely clear to me which updates I should expect via the "Stable" channel, but considering 17.0.5 is a security update, and released out of bounds so likely quite an important one. I feel that it should be the default offering through the Updater for any servers that are currently on NC17 to make sure that the security fix is as accessible as possible before is is disclosed.

The issue appears not be be isolated to my server only, https://help.nextcloud.com/t/any-way-to-use-the-updater-to-go-from-17-0-4-to-17-0-5/75103

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/18485

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/updater_server/pull/348

**Comment by giancarlobi** [comment]
@kesselb Sorry, but now for 17.0.3 is announced 18.0.3 and not 17.0.5:
https://updates.nextcloud.com/updater_server/?version=17x0x3x1xxxstablexx2020-01-29T21%3A23%3A47%2B00%3A00+b6a2f493bba6d372e9a8813041bf3928d54cf74bx7x2x19
```
<?xml version="1.0" encoding="UTF-8"?>
<nextcloud>
 <version>18.0.3.0</version>
 <versionstring>Nextcloud 18.0.3</versionstring>
 <url>https://download.nextcloud.com/server/releases/nextcloud-18.0.3.zip</url>
 <web>https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html</web>
 <changes>https://updates.nextcloud.com/changelog_server/?version=18.0.3</changes>
 <autoupdater>1</autoupdater>
 <eol>0</eol>
 <signature>rdvwW+bkw1MLNdy/9ojGkrGEwLsd7JU2sZ6rX4ZOFUBserLVR8QqyL0G0nJviiiC
kGWkFyMB56YNVyRp41EQfTkfEbdJprng/3xiP8fQP+EsLN9iNzW/bcmQMIMznler
dgR3Ye66jjAEuwETb+rmYu32Z6uWJw/I5N4qShhCwrDunY58nQqrO3v3js+yTtQA
gJHXyZWdFbLvhoV0PZ5vx7WqKL5y9EAFtgjTMK8gxVJu9Uic6Cg6tUjvyxlC9mQI
osQuvU+q91xvPbwqE8ig/nGnofAUYqZjDHeFSD6wSiMVw2dwuZnYv+E28pJbOGSD
02EIKzzu5XxDJVbRUKIirA==</signature>
</nextcloud>
```

**Comment by MorrisJobke** [comment]
> @kesselb Sorry, but now for 17.0.3 is announced 18.0.3 and not 17.0.5:

That's how it should be ... "stable" channel is for most recent stable minor version.

**Comment by kesselb** [comment]
I recall some discussions on GitHub and https://help.nextcloud.com. Actually the updater should always announce the latest minor before the next major.

**Comment by giancarlobi** [comment]
@kesselb I fully agree with you, thanks!

**Comment by MorrisJobke** [comment]
> I recall some discussions on GitHub and https://help.nextcloud.com. Actually the updater should always announce the latest minor before the next major.

We had it like that and also got complains, that you then need two steps to get to the next major version, which could be done in one step. So there is no perfect way of doing this.

**Comment by MorrisJobke** [comment]
Just to clear up a bit the confusing parts here. We had this feature in our production channel back then (see https://help.nextcloud.com/t/production-channel-removal/64223/10 for the removal reasons). Maybe we should think a bit more about this, but we clearly don't want to have instances run behind and are forgotten to be updated and then have a big gap that is hard to take, because just too much needed to be touched. Our primary goal is to bring as stable and secure software to our users. Thus we compromised on this one.

But maybe @rullzer or @jospoortvliet could also drop their opinion on this topic.

**Comment by sbw** [comment]
I agree with @giancarlobi and @kesselb: Nextcloud 18 will be a big step for me, because I'm planning to drop Collabora.  Until I'm ready to do that, I'm glad I can keep my Nextcloud 17 updated easily.  If Nextcloud doesn't offer minor releases through the updater, it will take me longer to update!

If there's a concern about instances "running behind," then work hard to refine the messaging around the updater.  It can say clearly explain why both minor and major releases are offered.  I've always found the updater messaging clear, but I understand others may need more clear messaging.

**Comment by kesselb** [comment]
A similar discussion at https://github.com/nextcloud/server/issues/18485 with some research why updater and updatenotification (app) show different versions.

Unfortunately it's a complex topic with many different opinions. My primary concern is to always announce the latest minor release. In the past we already run into various issue if people updated with outdated nextcloud and apps to a newer major release (groupfolders for example with a changed method signature). I also assume that the update path from latest 18.x.y to latest 19.x.y is the most widely tested path and most people should use it.

**Comment by MorrisJobke** [comment]
> It's still possible to roll out 19 in waves. But only to instances running the latest 18.x.y.

Yep. The updater server supports this. Then instead of "18" the latest version "18.0.4" is only provided with the 19 update. That's already available, used and working :) We just need to find a way to not make it more confusing (like adding another channel behaving slightly different)

**Comment by sbw** [comment]
Ugh.  While we're discussing this, the Nextcloud newsletter says it's time to update to 18.0.4, 17.0.6, and 16.0.10.  Both the newsletter and the updater offer https://nextcloud.com/changelog/ for full details.  **But none of those releases appear in the Changelog yet.**

I'll wait to update my instance to 17.0.6 until the Changelog is available.

In my instance, the 17.0.6 update is offered, but not the 18.0.4 update.  My experience is that after I apply the latest point release, Nextcloud then offers the next major release.  @MorrisJobke, I understand offering both caused a support burden in the past, so I'm actually cool with the current behavior, even if I'd prefer both.

**Comment by kesselb** [comment]
@sbw would you mind to not hijack this discussion? At GitHub and https://help.nextcloud.com are plenty of topics about the changelog thing. To give you a summary: It's always like that. If you feel better wait until the changelog is released.

**Comment by MorrisJobke** [comment]
> Ugh. While we're discussing this, the Nextcloud newsletter says it's time to update to 18.0.4, 17.0.6, and 16.0.10. Both the newsletter and the updater offer https://nextcloud.com/changelog/ for full details. **But none of those releases appear in the Changelog yet.**

@rullzer @jospoortvliet ?

**Comment by MorrisJobke** [comment]
> Yep. The updater server supports this. Then instead of "18" the latest version "18.0.4" is only provided with the 19 update. That's already available, used and working :) We just need to find a way to not make it more confusing (like adding another channel behaving slightly different)

Solved in the meantime. All channels do this.

**Comment by klawdhfzasjhaa** [comment]
> > I recall some discussions on GitHub and https://help.nextcloud.com. Actually the updater should always announce the latest minor before the next major.
> 
> We had it like that and also got complains, that you then need two steps to get to the next major version, which could be done in one step. So there is no perfect way of doing this.

Warning, includes personal opinion:
I see your points. But: In my view the nextcloud releases are major releases too often. Like Mozilla changed their release schema some time ago. Then a lot of new features are included, but real file sync dropbox-like features are abandond: https://github.com/nextcloud/android/issues/285. Even worse: Sometimes people's installations break after major updates. No offense, but it happens.

Back to topic: Why not offer an option via the updater.phar to choose from a version within a major version. Like: `updater.phar -iv | --install-version [version]`. This way the majority of the systems would still update fast, which is good for security of most systems. But it would also give users a choice to do the major update later and for the moment only install the minor update. FLOSS is about choice.

Example:

`sudo -u www-data php /var/www/nextcloud/updater/updater.phar -iv 19.0.5`

`Nextcloud Updater - version: v19.0.3-8-gbfdc40b
Current version is 19.0.4.
Update to Nextcloud 20.0.2 available (channel: "stable"). Will install 19.0.5 anyway because of user choice.`

What do you think?
