### ISSUE TITLE
Ability to Disable Web Updater

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/updater#281]
For nextcloud/server#18585.

The idea would be to have a second config option that prevents the updater from running from a web browser rather than the command line.

**Comment by kesselb** [comment]
A workaround until one implemented this feature: Let your webserver block requests to `/updater/index.php`.

**Comment by rveede** [comment]
I would also like to see this option added.

**Comment by nickvergessen** [comment]
The ability should be https://github.com/nextcloud/server/blob/7e6d69d166cbc92fb457fc72efc9abe850a0bbe4/config/config.sample.php#L1806-L1809 just needs to read the config

**Comment by PVince81** [comment]
PR for hiding the section in the admin settings: https://github.com/nextcloud/server/pull/25689

**Comment by PVince81** [comment]
PR for blocking index.php when config.php says it must be disabled: https://github.com/nextcloud/updater/pull/331

**Comment by szaimen** [comment]
@PVince81, #331 looks good, but I'd vote against hiding the section in the admin settings (nextcloud/server#25689) since it is still quite useful, if you can check in that section (also if you are performing updates only via CLI), if all apps have an update available for a new major NC update, since that is not possible via occ, afaik.

**Comment by szaimen** [comment]
This is now completely implemented, afaics.
