### ISSUE TITLE
Include database dump in updater backup

### ISSUE THREAD

**Issue by mmccarn** [nextcloud/updater#302]
My standard process when updating Nextcloud is to:
* rsync the current web folder to a backup location
* dump the database using mysqldump into my backup location
* run the web updater

```
cd /var/www
rsync -avz nextcloud/ nextcloud-19.0.2/
mysqldump --databases nextcloud |gzip >/var/www/nextcloud-19.0.2/nc-19.0.2.sql.gz
```

This gives me a complete backup that I feel I have some hope of restoring in a single location.

I would have the same if the web updater created a database backup during the 'backup' stage...

At first this would allow a system restore manually in case something goes really wrong during the upgrade.  Ultimately this could support a 'rollback' option in the updater itself - to roll back an update if some feature of the new version is objectionable to the server admin.

**Comment by MorrisJobke** [comment]
IMO this sounds easier than it is. The updater was designed to do only the bare minimum. And the backup stage only backups the stuff that the updater actually touches. Also we can't rely on external tools, because they may not be installed or executable from the web process. Thus we have a scriptable updater.phar which can be run in non-interactive mode (and also recently got a way to disable the backup stage to not duplicate the work of an external script). Just wrap your backup procedure in a shell script and then you have a working solution that fits your needs and your environment. And we don't add code that in some cases fail and cause more trouble.
