### ISSUE TITLE
Update Nextcloud: Move new files in place (Parsing response failed)

### ISSUE THREAD

**Issue by nichierichetti** [nextcloud/updater#369]
Hello everyone,

today I tried to upgrade the version of my nextcloud given the banner in the settings area.
Everything was going well but then it got stuck on Moving new files in place, giving this screen:

![2021-04-14 01_31_02-https___cloud openstudio one_updater_](https://user-images.githubusercontent.com/66752025/114633748-6a3dfa80-9cc1-11eb-8226-8fd72dd10109.jpg)

The detailed response is simply the HTML of the same page. I don't know what to do because If I refresh that page I am asked for the unhashed updater.secret which I cannot retrieve as OpenSSL is not supported by my hosting service.

What can I do? How can I go on or go back?

**Comment by MorrisJobke** [comment]
What is in the updater.log in the Nextcloud data directory written? It maybe gives a hint what went wrong here.

**Comment by proteus8** [comment]
I have the same problem attempting to upgrade from 21.0.0 to 21.0.2. However, there is no updater.log file in the data directory. Please advise.

**Comment by proteus8** [comment]
I added a updater.log file to the data folder, pressed Retry Update, and got the same message as listed by nichierichetti above. Even after the Retry Update, the updater.log file has a length of 0.
![image](https://user-images.githubusercontent.com/8278084/120258851-a284a280-c247-11eb-908a-9d46c2a83b64.png)

**Comment by nichierichetti** [comment]
The problem is still ongoing. It happened again with 21.0.7 update.
@Developers are you there?

**Comment by joshtrichards** [comment]
Is your `datadirectory` located on a different partition than your NC installation directory by chance?

**Comment by joshtrichards** [comment]
@nichierichetti:
> The problem is still ongoing. It happened again with 21.0.7 update.
@Developers are you there?

Yes, a log was requested the same week of your report but we never heard anything back:

https://github.com/nextcloud/updater/issues/369#issuecomment-824090097

So, again, please provide the `updater.log` from your `datadirectory` which gets written to each time you trigger an update.

In the meantime, the Nextcloud Admin Manual explains how to do:

- an update from the command-line 
- a manual update

Both processes can be found in the *Maintenance* section (see https://docs.nextcloud.com). The most reliable method is the command-line method since some web servers timeout on longer running aspects of the update process. Still other times a manual approach is necessary in environments with unusual filesystems/etc.

@proteus8 Perhaps your `datadirectory` is configured somewhere else and that's an old spot? Is the contents of the `updater-<instanceID>` fresh? In the mean time, you can try a command-line update and/or a manual update (see my above comments to the original poster).

**Comment by joshtrichards** [comment]
Closing due to lack of follow-up response and age.
