### ISSUE TITLE
Update fails by clicking Updater aufrufen

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/updater#39]
Hi, I received information form both of my NextCloud instances (V 9.0.51 & 10.0) that there an update is available. On the Version 10.0 (test installation) I switched to the admin panel an clicked on the button "_Updater aufrufen_"(Channel production)and **nothing** happened ! I changed the channel to stable...again, **nothing** happened on clicked on the button "_Updater aufrufen_" ! I tried the same procedure on my working installation (Version 9.0.51) ...again the same result:  **Nothing** happens ! No updater started!

I repeated the procedure 3 times...still the same result!

in config.php of both instances:
**updater.server.url' => 'https://updates.nextcloud.org/updater_server/',** 

regards, hitam4450

**Comment by MorrisJobke** [comment]
V 9.0.51 & 10.0 <- those versions still ship the old updater and should not be used with the updater.

Starting with 9.0.54 and 10.0.1 we ship the updater in this repo, which was more widely tested.

You could try following steps: https://help.nextcloud.com/t/help-testing-the-9-0-54rc1-and-10-0-1rc1/3254/6?u=morrisjobke (be aware: restart the webserver after replacing the files, because we have seen interferences here and it looks like cached versions of the old updater code)

But as you have trouble opening the updater at all: could you check the output in the web developer console? And also check if there are red requests in the network tab of the web developer console?

Nethertheless - please don't use the old updater - if you want to test this use the new one (see steps above) - the old one caused many serious problems.

**Comment by MorrisJobke** [comment]
This is the **new** (and working) updater:

![bildschirmfoto von 2016-09-29 10-05-25](https://cloud.githubusercontent.com/assets/245432/18945770/487d20c0-862c-11e6-9d70-aceb6d56e69a.png)

The **old** one (**don't click start here**) - you can see that there is a "Backup" entry in the left sidebar and a "Checkpoints" section at the bottom:

![bildschirmfoto von 2016-09-29 10-08-50](https://cloud.githubusercontent.com/assets/245432/18945882/c7c8de3c-862c-11e6-8a0c-74f85807882a.png)

**Comment by hitam4450** [comment]
Hi, @Morris!

Thank you very much for your comprehensive answer and information. Not every developer in team is so nice and patient like you, to explain and guide to the right solution! 

Ok, I agree that 9.0.51 won't be a version to support the "new" updater". Thats why I started with 
the "test" version 10.0. I remember, that in one of the numerous threads of this subject, it was said, 
that starting with version 10.0 it should not anymore be necessary to upgrade manually !

I just read your thread and would like to ask, where to put the updater script ??  In what place (directory) it should be placed ?? same as config.php ??

regards, hitam4450

**Comment by nickvergessen** [comment]
Put it in updater/ so, which should already exist (since you have the old one there as well)

**Comment by MorrisJobke** [comment]
> Ok, I agree that 9.0.51 won't be a version to support the "new" updater". Thats why I started with 
> the "test" version 10.0. I remember, that in one of the numerous threads of this subject, it was said, 
> that starting with version 10.0 it should not anymore be necessary to upgrade manually !

Sadly not. We just ship it with 10.0.1 :cry: 



> I just read your thread and would like to ask, where to put the updater script ?? In what place (directory) it should be placed ?? same as config.php ??

Into the folder `updater/` like @nickvergessen answered.

**Comment by hitam4450** [comment]
Ok & many thanks for your guidance ! @Morris @nickvergessen 
I'll give it a try!  :clap:  :satisfied:
regards, hitam4450
