### ISSUE TITLE
Update fails if 'lost+found' exists in data directory

### ISSUE THREAD

**Issue by c-schwamborn** [nextcloud/updater#390]
### Steps to reproduce
1.Update 21.0.x to 21.0.4 with a mounted filesystem (containing 'lost+found') at nextcloud/data

### Expected behaviour
it works

### Actual behaviour
it fails - complaining about 'access denied' errors, as 'lost+found' belongs to root in any case as it should be.

**Comment by cypress-hill-car** [comment]
Hi folks!
I got the same problem each few updates. My nextcloud filesystem ist very large ~10TB and it uses a couple of sub-mounted filesystems, so i can not solve this, by putting the data-folder in a subdirectory. The fs.mounts are part of data-structure, so I would prefer that the updater uses the forbidden-filenames-attrtibute of main config:

  'forbidden_filenames' =>
  array (
    0 => '.htaccess',
    1 => 'lost+found',
  ),

this would solve the fs.mount problems in all cases.

**Comment by c-schwamborn** [comment]
After the unsatisfactory answer from kesselb on Sep 20, 2021 i stopped pushing the issue, as he was unwilling to understand that this isn't a setup issue, but an updater issue. That attitude is sad and personally I don't understand it.

**Comment by kesselb** [comment]
Hi, and thanks for your follow-up.

There’s a newer ticket discussing a similar issue—please subscribe to it and use GitHub reactions if this is relevant to you: https://github.com/nextcloud/updater/issues/520.

The forbidden_filenames configuration option serves a completely different purpose, so it wouldn’t make sense to consider it in this context.

As mentioned back in 2021, Nextcloud’s updater assumes full control over the data directory, meaning that modifications by others aren’t supported. If there are folders in the data directory that weren’t created by Nextcloud, that’s considered a setup issue rather than a bug. 

If using a subdirectory as a workaround isn't an option for your setup, that’s still a configuration issue on your end. However, you can always use the manual upgrade method, which is documented here: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html. This approach is straightforward and can even be scripted if needed.

While we aim to support a wide range of configurations, it’s not feasible to accommodate every possible setup.

**Comment by c-schwamborn** [comment]
@joshtrichards thanks for cross linking that ticket and investigating the updaters behavior.
