### ISSUE TITLE
Updater is disabled....

### ISSUE THREAD

**Issue by Verdomme** [nextcloud/updater#392]
Ever since updating to 20.0.13 the auto-updater in NC tell me that the 'updater is disabled.please use the command line'.
Any fix for this issue (apart from updating manually :-) )

**Comment by Verdomme** [comment]
Not much help here

**Comment by joshtrichards** [comment]
@Verdomme Thanks for your report.

> Not much help here

That's because this isn't a tech support channel. It's for reporting bugs in the software. Reports are read to determine where to focus developer resources and prioritize enhancement work. Individual responses are not guaranteed. :-)

For technical support inquiries regarding your installation or troubleshooting your configuration the best place to post is the [Nextcloud Help Forum](https://help.nextcloud.com/).

The issue you have seems to be a local configuration matter as it appears you've disabled web upgrades in your `config.php`:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#upgrade-disable-web

Since you didn't provide your config I can't verify this with certainty, but that appears to be the case.

This Issue can be closed since it's not a bug.
