### ISSUE TITLE
Call `occ upgrade` with same php arguments as `updater.phar` is called?

### ISSUE THREAD

**Issue by jneuhauser** [nextcloud/updater#468]
I'm calling the updater with: `/usr/bin/php8.1 --define apc.enable_cli=1 /var/www/nextcloud/updater/updater.phar --no-interaction`

But while doint the full update, the command `occ upgrade` fails with: `OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)`

Is it possible that `updater.phar` calls `occ upgrade` also with `--define apc.enable_cli=1`?

**Comment by joshtrichards** [comment]
Good catch. I'm kind of surprised it hasn't come up before. Maybe most people just workaround it. :thinking: 

We call `occ` in two places:

https://github.com/nextcloud/updater/blob/aac9e4b1f9edc88a0d28dcbfca50276c9a2c25ba/lib/UpdateCommand.php#L312

https://github.com/nextcloud/updater/blob/aac9e4b1f9edc88a0d28dcbfca50276c9a2c25ba/lib/UpdateCommand.php#L330

I see no reason we can't specify `--define apc.enable_cli=` by default when calling `occ` from the updater since it's the recommended default (and it shouldn't hurt to specify it even if the local admin has, say, already enabled it in their `php.ini`).

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html?highlight=enable_cli#using-the-command-line-based-updater

PRs are welcome if you want to try. :-)

P.S. It's too bad `apc.enable_cli` is only `PHP_INI_SYSTEM` changeable so we're not allowed to set it via `ini_set()` ourselves in `occ` & `updater`.

**Comment by joshtrichards** [comment]
Closing since this is no longer applicable / was addressed in a different way. See:

nextcloud/server#46151

nextcloud/documentation#12332
