### ISSUE TITLE
Bug: Check for expected files fails when logfile is configured

### ISSUE THREAD

**Issue by Yannik** [nextcloud/updater#482]
I have configured `'logfile' => 'nextcloud.log',`  in `config/config.php`. 

Trying to update from 27.0.0 to 27.0.1, the upgrade fails during the `Check for expected files` phase:

![Screenshot from 2023-07-26 12-07-27](https://github.com/nextcloud/updater/assets/801996/a1adbf7d-7b7f-4228-a051-f12d9f87af93)

Expected behavior: This should not occur, because the `nextcloud.log` file is actually expected to be there, as it is configured as logfile.

**Comment by Yannik** [comment]
Note that `'logfile' => 'nextcloud.log'` exactly matches the [example in the documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#file).

**Comment by joshtrichards** [comment]
Hi @Yannik - Where is there? In the webrot? Are you sure that's your currently active `nextcloud.log` and not an old/stale `nextcloud.log`? When configured as you stated, the log file will be in your configured `datadirectory` (not webroot) and thus excluded from the expected files check.

**Comment by kesselb** [comment]
Why would you put nextcloud.log in the root directory :thinking: 

Your bug report is valid from a technical point because we don't add the configured logfile automatically to the list of expected files. 

I don't see a good reason why someone would place the logfile there and therefore close the issue.
