### ISSUE TITLE
[Bug]: The Longstanding Nightmare of Nextcloud's Update Process

### ISSUE THREAD

**Issue by x011** [nextcloud/updater#502]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The ongoing issues with the update process are both absurd and inexcusable. It's apparent that those responsible for it are utterly unfit for the job. A quick review of the numerous topics concerning Nextcloud server updates provides enough evidence of this chaos. 

A supposedly straightforward update from version 25.0.7 to 25.0.10 on an Ubuntu server results in a bombardment of errors. When the update process fails, it frustratingly hangs at "Update Nextcloud on step X."

Executing the `sudo -u www-data php --define apc.enable_cli=1 /var/www/html/nextcloud/updater/updater.phar` command should be straightforward, but instead, it is plagued with problems:

```
Current version is 25.0.7.

Update to Nextcloud 25.0.10 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.10.zip
Open changelog ↗️

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔️] Check for expected files
[✔️] Check for write permissions
[✔️] Create backup
[✔️] Downloading
[✔️] Verify integrity
[ ] Extracting ...PHP Warning:  require(/var/www/html/nextcloud/updater/../version.php): failed to open stream: No such file or directory in phar:///var/www/html/nextcloud/updater/updater.phar/lib/Updater.php on line 673
PHP Fatal error:  require(): Failed opening required '/var/www/html/nextcloud/updater/../version.php' (include_path='.:/usr/share/php') in phar:///var/www/html/nextcloud/updater/updater.phar/lib/Updater.php on line 673
```
This isn't just an isolated technical hiccup, but a critical error indicating a disastrous lack of competence. 

In no uncertain terms, the team handling this update process needs to be seriously reevaluated. Perhaps they should be replaced by individuals who can competently manage and streamline the process - because as it stands, this is an organizational catastrophe.

---

There appears to be a potential [workaround](https://help.nextcloud.com/t/update-stuck-on-step-6-extracting/106321/2) to this persistent error, although it remains untested. However, when we delve into this, it's quite startling to see the extent of hoops a user is expected to jump through just to update Nextcloud. This workaround isn't simply a convenient detour – it's a complex, multi-step hurdle that users are being forced to navigate. Such a process should surely be more streamlined, with less burden on the user. This situation highlights the need for an urgent review of the update process within Nextcloud.

### Steps to reproduce

1. sudo -u www-data php --define apc.enable_cli=1 /var/www/html/nextcloud/updater/updater.phar

### Expected behavior

Update nextcloud from version 25.0.7 to 25.0.10

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Could not open input file: occ
```

### List of activated Apps

```shell
Could not open input file: occ
```

### Nextcloud Signing status

```shell
Update in process.
```

**Comment by n0valis** [comment]
@joshtrichards 
> The updater app isn't part of `server`

It is however part of the latest server tarball
https://download.nextcloud.com/server/releases/latest.zip

**Comment by AdamAnon** [comment]
I've run Nextcloud for about 6 months now. Every single Nextcloud update breaks something or generates errors on  the admin page for me and requires googling around for solution, fixing and tweaking to get it working properly again. 

This is a very clean, lean, simple, basic installation on standalone, dedicated Ubuntu server (Dell Optiplex) with Apache, (not shared hosting, real hardware), single user, no extra apps, just the defaults, nothing else is running on this box, only what's needed to run Nextcloud, hardware: SSD, 6th gen Core i5, 16GB of RAM, gigabit fiber, gigabit LAN. 

I came to dread Nextcloud updates and every time I'm closer to paying again for Dropbox. When it works, it works well, but the updates are a complete nightmare, both the web updater and the command line. In 6 months I had to reinstall once already because update just flatout broke the installation. Trying to run an update today and it's been sitting stuck "downloading" for over an hour now. 

Don't tell me "it's your problem", because it's not, my installation can't be any more simple and straightforward, Ubuntu always kept updated. The problem is the Nextloud installer/updater.

**Comment by joshtrichards** [comment]
@AdamAnon I encourage you to open a dedicated issue with the details of your situation.

**Comment by AdamAnon** [comment]
> @AdamAnon I encourage you to open a dedicated issue with the details of your situation.

Thank you but it has been an ongoing thing with each and every update and I'm sort of burnt out. Today, it eventually finished after over 2 hours. I've run multiple network tests during that time and was getting ~800Mbps down and 300Mbps up from the server, no reason for the download to take that long, there was barely any CPU, RAM and disk activity, the updater just stalled. Luckily though, this time everything seems to be working past the patch and I see no errors in Admin overview page. So I'm gonna just leave it at that. If I have a problem again with future updates, I'll open an issue. 

The thing is that outside of the updates Nextcloud works so beautifully when it works, installation and setup is easy, so it's so frustrating when you have to deal with such problematic updates. I sync around 1TB across four Windows 11 PCs, an iPhone, an iPad and a Moto Android phone using about $200 worth of old hardware and it *just works*.

**Comment by petre2dor** [comment]
Hi @AdamAnon, 
I don't really know much about this stuff, but I have a similar issue that seems to get fixed by disabling zfs sync on the pool where nextcloud data is. Are you using zfs and or nfs? 
I got a clue about this from this video: https://www.youtube.com/watch?v=R7BXEuKjJ0k&t=1313s

I hope this helps...

**Comment by AdamAnon** [comment]
Hi @petre2dor,
Thanks, but no ZFS, it's just a simple ext4 volume, most basic setup possible :)

**Comment by dorald** [comment]
Just came here from google. I've the same Nextcloud Update Nightmare every single time I update the Nextcloud.
Today the update broken again and I can't access my files anymore. 
I decided to search for another solution and abandon NextCloud for good.

**Comment by Somapolice** [comment]
Same issues here. Every time I update I start getting a deluge of php errors and have to go back and delete then rebuild Nextcloud from scratch. I cringe whenever I see an update available. I am on Debian 12 in an LXC with my data directory on a bind mounted drive.

PHP Warning:  rmdir(BINDMOUTDIRECTORY/NextCloud/data/updater-ocd1ez8buwba/downloads/nextcloud/apps/suspicious_login/vendor/rubix/ml/tests/Datasets): No such file or directory in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 792

...is one of hundreds that flash on my screen during the download step.

I then get:

[ ] Move new files in place ...PHP Warning:  rename(BINDMOUNTDIRECTORY/NextCloud/data/updater-ocd1ez8buwba/downloads/nextcloud/ocs/v2.php): Failed to open stream: No such file or directory in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 934
PHP Warning:  rename(BINDMOUNTDIRECTORY/NextCloud/data/updater-ocd1ez8buwba/downloads/nextcloud/ocs/v2.php,/var/www/nextcloud/updater/../ocs/v2.php): No such file or directory in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 934
[✘] Move new files in place failed
Could not rename BINDMOUNTDIRECTORY/NextCloud/data/updater-ocd1ez8buwba/downloads/nextcloud/ocs/v2.php to /var/www/nextcloud/updater/../ocs/v2.php

Update failed. To resume or retry just execute the updater again.

I get the same thing every incremental update

**Comment by dorald** [comment]
I replaced NextCloud with Seafile and I'm happy with it, works as excepted. No more nightmares.

**Comment by gioman** [comment]
Why has this been closed? Isn't out there enough evidence (just search your forum) that there is something that is not right? I started an upgrade process (from CLI ) more than 1 hour ago, and it is still stuck on step 6, "extracting" (after more or less 30 minutes on step 3, "backup"). This happens on any machine (ubuntu server LTS) where I deployed NC.

**Comment by AdamAnon** [comment]
I haven't updated Nextcloud since November, because I'm too afraid it would break again. I'm just a single user so I can do that, but I feel bad for those who manage NC for larger organizations.

**Comment by joshtrichards** [comment]
@Somapolice It would be best if you create a dedicated issue so that your situation can be looked specifically into and tracked until resolved. Does your `datadirectory` by chance point at a symlink (for example, if you moved your data directory to that other drive/mount post-installation)? Or are there any symbolic links involved elsewhere within your Nextcloud related folders?

@gioman This issue is closed because the original reporter didn't provide needed details, lacked access to `occ` (suggesting a non-standard installation), and they had no interest in continuing to look into the matter when queried. The comments here in this issue are not all occurring in the same Step of the Updater. And we need individual reports from each of you to look into your specific situation(s).

## Anyone else arriving here: *Please* open a dedicated issue with your situation so that your report can be looked at. Commenting on a random closed thread w/o sufficient details about your specific situation is unlikely to get the help or results you're hoping for.

**Comment by dorald** [comment]
@joshtrichards instead of suggesting to 'open dedicated issue' just collect the actual information including this threads comments and work fixing the problems. I personally and my company I work for, abandoned NextCloud and we are happy with but I'd love to see progress and user care from another file hosting services including NC.

**Comment by joshtrichards** [comment]
@dorald That's not realistic. Many of the comments in here lack sufficient information about their environment. And this will just become a "catch all" for every bug report about the Updater. One bug or enhancement per Issue.  It makes no sense to try to tackle reports that lack information or to follow-up asking for more information here -- triggering everyone that has ever commented to get emails and generating extra noise. It also makes it impossible to track which bugs are fixed and which aren't.

**Comment by jcvikl** [comment]
I got also same problem with 25...Message - Execution filemng has failed with exit code 255, stdout: Nextcloud Updater - version: v25.0.0beta3-17-gef6cf2d Current version is 25.0.1. Update to Nextcloud 25.0.13 available. (channel: "stable") Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.13.zip Open changelog ↗ Updater run in non-interactive mode. Start update Info: Pressing Ctrl-C will finish the currently running step and then stops the updater. [ ] Check for expected files ... [2K[✔] Check for expected files [ ] Check for write permissions ... [2K[✔] Check for write permissions [ ] Create backup ... [2K[✔] Create backup [ ] Downloading ... [2K[✔] Downloading [ ] Verify integrity ..., stderr: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 186434464 bytes) in phar:///var/www/vhosts/xyz.com/httpdocs/updater/updater.phar/lib/Updater.php on line 654 There is no updater.phar/lib/Updater.php because updater.phar is a file. Does anybody know how is back migration from next to own cloud?
